name: safana_bekam_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.20.0
  open_file: ^3.5.4
  path_provider: ^2.1.4
  pdf: ^3.11.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/image/body/body_front.png
      - assets/image/body/body_back.png
      - assets/image/body/face.png
      - assets/image/skin_reaction.png
      - assets/image/logo.png
      - assets/image/background_app.png
      - assets/image/background_circle.png
      - assets/image/image_no_available.jpg
